project 'UPK-GE01.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UPK-GE01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UPK-GE01
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'Hero'
  pod 'SVGKit'
  pod 'FacebookSDK'

end
